"""Update models structure and add new fields

Revision ID: 423ac6ccd7e1
Revises: 64e0bce85228
Create Date: 2025-11-15 09:16:35.316801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423ac6ccd7e1'
down_revision: Union[str, Sequence[str], None] = '64e0bce85228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='Название товара'),
    sa.Column('unit', sa.String(), nullable=True, comment='Единица измерения'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_table('supplier_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='ID поставщика'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='ID товара'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'product_id', name='uq_supplier_product')
    )
    op.create_index(op.f('ix_supplier_products_id'), 'supplier_products', ['id'], unique=False)
    op.create_table('supplier_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='ID поставщика'),
    sa.Column('rule_text', sa.Text(), nullable=False, comment='Текст правила с маркерами [PRODUCT:id]'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='Приоритет правила (чем меньше, тем выше)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Активность правила'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_rules_id'), 'supplier_rules', ['id'], unique=False)
    op.create_table('history_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=False, comment='ID записи истории'),
    sa.Column('order_item_id', sa.Integer(), nullable=False, comment='ID элемента заказа'),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('history_id', 'order_item_id', name='uq_history_order_item')
    )
    op.create_index(op.f('ix_history_order_items_id'), 'history_order_items', ['id'], unique=False)
    # Используем batch mode для SQLite, так как он не поддерживает ALTER для внешних ключей
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True, comment='ID заказа'))
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True, comment='ID поставщика'))
        batch_op.create_foreign_key('fk_history_supplier_id', 'suppliers', ['supplier_id'], ['id'])
        batch_op.create_foreign_key('fk_history_order_id', 'orders', ['order_id'], ['id'])
    
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sent_to_supplier', sa.Boolean(), nullable=True, comment='Статус отправки товара поставщику'))
        batch_op.alter_column('order_id', existing_type=sa.INTEGER(), nullable=False)
    op.add_column('orders', sa.Column('is_closed', sa.Boolean(), nullable=True, comment='Статус закрытия заказа (в MVP заводим, но в логике не используем)'))
    op.add_column('points', sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='Флаг мягкого удаления'))
    op.add_column('suppliers', sa.Column('email', sa.String(), nullable=True, comment='Email поставщика (с валидацией формата)'))
    op.add_column('suppliers', sa.Column('telegram', sa.String(), nullable=True, comment='Telegram (логин или ID)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'telegram')
    op.drop_column('suppliers', 'email')
    op.drop_column('points', 'is_deleted')
    op.drop_column('orders', 'is_closed')
    
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('order_id', existing_type=sa.INTEGER(), nullable=True)
        batch_op.drop_column('is_sent_to_supplier')
    
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_history_order_id', type_='foreignkey')
        batch_op.drop_constraint('fk_history_supplier_id', type_='foreignkey')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('order_id')
    op.drop_index(op.f('ix_history_order_items_id'), table_name='history_order_items')
    op.drop_table('history_order_items')
    op.drop_index(op.f('ix_supplier_rules_id'), table_name='supplier_rules')
    op.drop_table('supplier_rules')
    op.drop_index(op.f('ix_supplier_products_id'), table_name='supplier_products')
    op.drop_table('supplier_products')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
