"""Add product_type field to Product

Revision ID: 57f0aaff1e82
Revises: 423ac6ccd7e1
Create Date: 2025-11-15 09:29:53.235610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f0aaff1e82'
down_revision: Union[str, Sequence[str], None] = '423ac6ccd7e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Используем batch mode для SQLite операций с существующими таблицами
    with op.batch_alter_table('history', schema=None) as batch_op:
        # Проверяем, не существуют ли уже внешние ключи
        try:
            batch_op.create_foreign_key('fk_history_order_id', 'orders', ['order_id'], ['id'])
        except:
            pass
        try:
            batch_op.create_foreign_key('fk_history_supplier_id', 'suppliers', ['supplier_id'], ['id'])
        except:
            pass
    
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sent_to_supplier', sa.Boolean(), nullable=True, comment='Статус отправки товара поставщику'))
        try:
            batch_op.alter_column('order_id', existing_type=sa.INTEGER(), nullable=False)
        except:
            pass
    
    op.add_column('orders', sa.Column('is_closed', sa.Boolean(), nullable=True, comment='Статус закрытия заказа (в MVP заводим, но в логике не используем)'))
    op.add_column('points', sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='Флаг мягкого удаления'))
    op.add_column('product', sa.Column('product_type', sa.String(), nullable=True, comment='Вид товара (категория)'))
    op.add_column('suppliers', sa.Column('email', sa.String(), nullable=True, comment='Email поставщика (с валидацией формата)'))
    op.add_column('suppliers', sa.Column('telegram', sa.String(), nullable=True, comment='Telegram (логин или ID)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'telegram')
    op.drop_column('suppliers', 'email')
    op.drop_column('product', 'product_type')
    op.drop_column('points', 'is_deleted')
    op.drop_column('orders', 'is_closed')
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('order_items', 'is_sent_to_supplier')
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_constraint(None, 'history', type_='foreignkey')
    # ### end Alembic commands ###
