"""Add address and note fields to Point

Revision ID: dfc50b21bca5
Revises: 57f0aaff1e82
Create Date: 2025-11-15 09:47:51.682818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc50b21bca5'
down_revision: Union[str, Sequence[str], None] = '57f0aaff1e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Проверяем существование колонок перед добавлением
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_columns = [col['name'] for col in inspector.get_columns('points')]
    
    if 'address' not in existing_columns:
        op.add_column('points', sa.Column('address', sa.String(), nullable=True, comment='Адрес точки продаж'))
    
    if 'note' not in existing_columns:
        op.add_column('points', sa.Column('note', sa.Text(), nullable=True, comment='Примечание'))
    
    # Используем batch mode для SQLite, так как он не поддерживает ALTER для изменения nullable
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.alter_column('owner',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('points', 'owner',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('points', 'note')
    op.drop_column('points', 'address')
    # ### end Alembic commands ###
