"""remove_contact_from_suppliers

Revision ID: f3f27c8a9139
Revises: 890326fb26b8
Create Date: 2025-11-18 10:05:39.641835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f27c8a9139'
down_revision: Union[str, Sequence[str], None] = '890326fb26b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Используем batch_alter_table для SQLite
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('is_sending_to_supplier',
                   existing_type=sa.INTEGER(),
                   type_=sa.Boolean(),
                   existing_nullable=True,
                   existing_server_default=sa.text('0'))
        batch_op.create_foreign_key('fk_order_items_suppliers_id', 'suppliers', ['suppliers_id'], ['id'])
        batch_op.create_foreign_key('fk_order_items_product_id', 'product', ['product_id'], ['id'])
    op.drop_column('suppliers', 'contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('contact', sa.VARCHAR(), nullable=True))
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_items_product_id', type_='foreignkey')
        batch_op.drop_constraint('fk_order_items_suppliers_id', type_='foreignkey')
        batch_op.alter_column('is_sending_to_supplier',
                   existing_type=sa.Boolean(),
                   type_=sa.INTEGER(),
                   existing_nullable=True,
                   existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
